### ISSUE TITLE
RxPY

### ISSUE THREAD

**Issue by axgkl** [sfermigier/awesome-functional-python#10]
Hi - many thanks for this extensive list, found a few really interesting libs!

One thing: ReactiveX is pretty spread meanwhile in the industry. I know, its considered slightly different to functional programming but still.
And the [RxPY](https://github.com/ReactiveX/RxPY/tree/release/v1.6.x) implementation is really serious, absolutely feature complete, we use it in production - and it offers more than the JS or Java implementation - but still, due to a private effort of one guy (not me) dependent on some marketing, so:

> I think RxPY should get its stars mentioned - since I think it is well within the top 5 most popular libs on your list &  and it really deserves it - there are some books around that specific Rx implementation :-)

**Comment by sfermigier** [comment]
Hi, sorry for the late reply. I'm too lazy to update the star counts, but I'll write a script someday to automate the process...

**Comment by sfermigier** [comment]
I've written a script to update the star counts. RxPy is indeed the most popular project from the list.
