### ISSUE TITLE
Is this article on scope?

### ISSUE THREAD

**Issue by sobolevn** [sfermigier/awesome-functional-python#14]
I am not sure about this article: https://sobolevn.me/2019/03/enforcing-srp

Should I submit it or not? It is a purely functional approach, but not so widely used.

**Comment by sfermigier** [comment]
Yes. It's not 100% on target, but it's a good article (like the other you've submitted, BTW).

**Comment by sobolevn** [comment]
Thanks a lot! Submitted.
