### ISSUE TITLE
Include unpythonic: Lisp/Haskell features for Python?

### ISSUE THREAD

**Issue by Technologicat** [sfermigier/awesome-functional-python#17]
Recently, I've been cooking up a library called [unpythonic](https://github.com/Technologicat/unpythonic) that adds Lisp and Haskell inspired features into Python.

There's a core of functionally oriented stuff that runs on bare Python, plus `unpythonic.syntax`, a collection of language features implemented in [MacroPy3](https://github.com/azazel75/macropy), including `let`/`let*`/`letrec` constructs, automatic TCO, automatic currying, lazy functions (call-by-need), and continuations (call/cc).

[It's on PyPI](https://pypi.org/project/unpythonic/).

What do you think, is it on topic?

**Comment by sfermigier** [comment]
Done, yes it looks quite cool.
