### ISSUE TITLE
Result?

### ISSUE THREAD

**Issue by kandhan-kuhan-t** [sfermigier/awesome-functional-python#22]
I came across this [Result](https://github.com/dbrgn/result) - Rust like return types.
This is very smaller in scope compared to [Returns](https://github.com/dry-python/returns) but quite nice. 
Belongs here?

**Comment by xkortex** [comment]
Seconded. Result is smaller in scope, but the interfaces are lighter, which is a win in my opinion. Returns currently calls a rather involved call stack when you map things (since it goes through the generic applicative interface) so it's a little less direct.

**Comment by sfermigier** [comment]
Thanks !
