### ISSUE TITLE
Talk + library: PyCon 2022

### ISSUE THREAD

**Issue by vickumar1981** [sfermigier/awesome-functional-python#27]
Hi.  would you mind adding my talk and library to this list?

I've used some of these libraries before like pymonad, but I didn't really want the base classes like functor, associative, etc.  I just wanted the following Monads - Try, Either, Option, etc., so I made a small library for it.

Talk: https://www.youtube.com/watch?v=x7sQVLO3JJA
Library:  https://github.com/vickumar1981/pyeffects
Docs: https://pyeffects.readthedocs.io/en/latest/?badge=latest

Thanks!

**Comment by sfermigier** [comment]
Cool, thanks. I'll watch the vid when I have the time.
